// Single source of truth for everything on the page.
// Facts here are taken from the CV, the NeoRecruit codebase and its production
// logs — keep them accurate. No invented metrics.

export const site = {
  name: "Suriya Prasath M",
  role: "AI Engineer",
  url: "https://suriyaprasath248.github.io/Portfolio/",
  location: "Coimbatore, India",
  description:
    "AI engineer building real-time AI systems in production: voice interviews with LLMs, speech pipelines, computer-vision proctoring and semantic CV matching. Sole engineer on NeoRecruit.AI.",
  email: "m.s.prasath5818@gmail.com",
  links: {
    github: "https://github.com/SuriyaPrasath248",
    linkedin: "https://www.linkedin.com/in/suriya-prasath-m-0506ba165/",
    x: "https://x.com/MSPrasath5818",
    xHandle: "@MSPrasath5818",
  },
};

export const hero = {
  kicker: "AI Engineer · Technical Lead at NeoRecruit.AI",
  headlineA: "I build AI that",
  rotating: ["listens.", "talks back.", "watches.", "judges fairly."],
  lede:
    "Three years as the sole engineer of an AI interviewer that real hiring teams use. Speech-to-text, LLM conversation, voice and avatar, in-browser vision and structured LLM scoring, wired together in real time.",
  facts: [
    { value: "3+", label: "years shipping AI to production" },
    { value: "50+", label: "cloud functions I run" },
    { value: "~90%", label: "less manual screening in pilots" },
  ],
};

// One real interview turn, as it appears in production logs (latencies rounded).
export const liveTurn = [
  { t: "00.00", tag: "mic", text: "answer recorded · 0.33 MB · peak RMS 0.21 ✓ speech" },
  { t: "01.09", tag: "stt", text: "whisper + deepgram → transcript (1.1 s)" },
  { t: "02.62", tag: "llm", text: "follow-up question generated (1.2 s)" },
  { t: "03.00", tag: "tts", text: "voice synthesised (0.38 s)" },
  { t: "03.10", tag: "avatar", text: "streaming to avatar · lip-sync" },
  { t: "∞", tag: "vision", text: "face / person / gaze checks running in browser" },
];

export type PipelineNode = {
  id: string;
  label: string;
  sub: string;
  detail: string;
};

export type PipelineLane = {
  id: string;
  title: string;
  nodes: PipelineNode[];
};

export const pipeline: PipelineLane[] = [
  {
    id: "screen",
    title: "Screening",
    nodes: [
      { id: "cv", label: "CV upload", sub: "bulk PDF / DOCX", detail: "Recruiters drop hundreds of CVs at once. Files are parsed into structured profiles on Cloud Run." },
      { id: "embed", label: "Embed", sub: "OpenAI embeddings", detail: "Each CV and the job description become vectors, so matching is semantic rather than keyword overlap." },
      { id: "vec", label: "Vector search", sub: "Pinecone", detail: "Candidates are ranked against the role by similarity, then shortlisted for the AI interview." },
    ],
  },
  {
    id: "interview",
    title: "Live interview",
    nodes: [
      { id: "mic", label: "Mic", sub: "WebAudio meter", detail: "A loudness meter gates silent or dead-mic recordings before they reach speech-to-text, because STT models invent words on silence." },
      { id: "stt", label: "Speech → text", sub: "Whisper + Deepgram", detail: "Two transcribers run together: one for clean text, one raw for auditing what was actually said." },
      { id: "llm", label: "LLM", sub: "GPT follow-ups", detail: "The model sees the job, the CV and the whole conversation and asks the next question, in the recruiter's language." },
      { id: "voice", label: "Voice + avatar", sub: "TTS · WebRTC", detail: "Replies are synthesised and streamed to a real-time avatar, with sessions rotated before the provider's 20-minute expiry." },
    ],
  },
  {
    id: "integrity",
    title: "Integrity",
    nodes: [
      { id: "cam", label: "Camera", sub: "browser only", detail: "No video leaves the device for proctoring. Everything runs locally in the candidate's browser." },
      { id: "vision", label: "Vision models", sub: "MediaPipe", detail: "Face and person detection on an adaptive cycle, plus iris-based gaze tracking with calibration." },
      { id: "flags", label: "Risk score", sub: "violations log", detail: "Tab switches, extra people, extra monitors and missing faces roll up into a reviewable risk score." },
    ],
  },
  {
    id: "eval",
    title: "Evaluation",
    nodes: [
      { id: "schema", label: "Criteria → schema", sub: "function calling", detail: "The recruiter's own scoring criteria become a function-calling schema, so scores come back typed, not parsed from prose." },
      { id: "score", label: "Scores", sub: "per metric", detail: "Each metric gets a numeric score and written reasoning grounded in the transcript." },
      { id: "aicheck", label: "AI-answer check", sub: "second LLM pass", detail: "A second pass estimates how likely the answers were generated by an AI rather than the candidate." },
    ],
  },
];

export type Highlight = {
  title: string;
  body: string;
  visual: "wave" | "chunks" | "face" | "timer" | "schema";
  span?: "wide" | "tall";
};

export const highlights: Highlight[] = [
  {
    title: "Stopped speech-to-text from inventing answers",
    body: "Candidates with a muted mic were getting transcript lines they never said. A WebAudio analyser now meters every take and blocks silence before transcription.",
    visual: "wave",
    span: "wide",
  },
  {
    title: "Structured LLM scoring",
    body: "Recruiter criteria compile into a function-calling schema at submit time, so every metric comes back as a typed number with reasoning.",
    visual: "schema",
    span: "tall",
  },
  {
    title: "Vision proctoring in the browser",
    body: "Face, person and gaze models run client-side on an adaptive cycle. Nothing is uploaded for analysis.",
    visual: "face",
  },
  {
    title: "Avatars that outlive their session",
    body: "Provider sessions expire at ~20 minutes; interviews run to 50. Sessions hot-swap on a 17-minute schedule, between sentences.",
    visual: "timer",
  },
  {
    title: "Recording that survives a crash",
    body: "Avatar and mic mixed into one track, uploaded in chunks with retry, then merged and re-encoded across sessions with FFmpeg on Cloud Run.",
    visual: "chunks",
    span: "wide",
  },
];

export const stack = [
  "OpenAI", "Whisper", "Deepgram", "Function calling", "Embeddings", "Pinecone",
  "MediaPipe", "WebRTC", "WebAudio", "FFmpeg", "Python", "Node.js",
  "React", "Next.js", "Firebase", "Cloud Run", "Firestore", "TypeScript",
];

export type XrProject = { title: string; image: string; href: string; tag: string };

// Earlier career, kept short on purpose.
export const xrProjects: XrProject[] = [
  { title: "Kochi Metro Rail VR", image: "/images/km.webp", href: "https://www.youtube.com/watch?v=e3R1MZmnR-w", tag: "Best Booth, 15th UMI" },
  { title: "Kochi Water Metro VR", image: "/images/wm.webp", href: "https://www.youtube.com/watch?v=ITmuylA6ypc", tag: "KMRL" },
  { title: "Airport Logistics", image: "/images/atvr.webp", href: "https://drive.google.com/file/d/1Hxz0xkzJ5mI2Y1n9TxmHIabys5ufx8QQ/view", tag: "4× faster training" },
  { title: "Federal Bank Gold Testing", image: "/images/fb.webp", href: "https://drive.google.com/file/d/1SMDjeqQj4UlSI-T0Iged9mvKXSRXUUFg/view", tag: "Banking" },
  { title: "Faulty Wire Tracing", image: "/images/fw.webp", href: "https://drive.google.com/file/d/1I_oOc0Wpujjc5qLqiRyOlo3Ph4766b0q/view", tag: "AR · IoT twin" },
  { title: "Virtual Tourism", image: "/images/vt.webp", href: "https://drive.google.com/file/d/1qcrnDiVZe_6Izs8CDKLxCfD8Tc4YZxFV/view", tag: "Photogrammetry" },
];

export const caseLink = {
  href: "https://drive.google.com/drive/folders/1dkLr_a_FP6tSRGLgea1pSVbjhJiK-xN6?usp=sharing",
  label: "Product walkthrough",
};

export const roles = [
  {
    when: "Jul 2023 — now",
    title: "Software Developer → Technical Lead",
    org: "NeoRecruit.AI",
    where: "Coimbatore",
    body: "Sole engineer on an AI hiring platform: LLM interviews, speech, vision proctoring, CV matching and the cloud underneath. Led the move from a Unity WebGL prototype to the React product.",
  },
  {
    when: "Nov 2022 — Jul 2023",
    title: "Unity XR Developer",
    org: "XR Horizon",
    where: "Kochi",
    body: "Industrial and transport VR simulations for KMRL, Britco and Federal Bank.",
  },
  {
    when: "Sep 2021 — Oct 2022",
    title: "Unity Developer, Intern",
    org: "GrahasVR · Nandha Infotech",
    where: "Remote",
    body: "Mobile VR safety training and educational AR.",
  },
];

export const education = {
  when: "2019 — 2023",
  title: "B.Tech, Information Technology",
  org: "Bannari Amman Institute of Technology",
};

export const recognition = [
  { title: "Smart India Hackathon 2022", body: "National finalist." },
  { title: "Best Booth, 15th Urban Mobility Conference", body: "KMRL VR simulation." },
  { title: "WorldSkills 2021", body: "Wild-card entrant, 3D Game Art; later trained BRICS and WorldSkills medallists." },
];
