// Single source of truth for everything on the page.
// Facts here are taken from the CV and the NeoRecruit codebase — keep them accurate.

export const site = {
  name: "Suriya Prasath M",
  role: "Software Engineer",
  url: "https://suriyaprasath248.github.io/Portfolio/",
  location: "Coimbatore, India",
  description:
    "Software engineer building real-time AI interview systems. Sole engineer on NeoRecruit.AI — streaming avatars, speech pipelines, in-browser proctoring. Previously VR training simulations.",
  email: "m.s.prasath5818@gmail.com",
  links: {
    github: "https://github.com/SuriyaPrasath248",
    linkedin: "https://www.linkedin.com/in/suriya-prasath-m-0506ba165/",
    x: "https://x.com/MSPrasath5818",
    xHandle: "@MSPrasath5818",
  },
};

export const hero = {
  kicker: "Technical Lead · NeoRecruit.AI",
  headline: "Software engineer building real-time AI interview systems.",
  lede:
    "Sole engineer on NeoRecruit.AI for three years — streaming avatars, speech pipelines, in-browser proctoring, and the cloud underneath. Before that, VR training simulations for banks, metros and airports.",
  facts: [
    { value: "3+", label: "years, sole engineer" },
    { value: "50+", label: "cloud functions in production" },
    { value: "10", label: "XR projects shipped" },
  ],
};

export const caseStudy = {
  name: "NeoRecruit.AI",
  period: "2023 — now",
  role: "Software Developer → Technical Lead",
  href: "https://drive.google.com/drive/folders/1dkLr_a_FP6tSRGLgea1pSVbjhJiK-xN6?usp=sharing",
  hrefLabel: "Product walkthrough",
  summary: [
    "An AI hiring platform, built end to end. Recruiters upload CVs in bulk, the system scores them against the job with embeddings, and candidates take a live interview with a streaming avatar — transcribed, follow-ups generated by an LLM, recorded and proctored. Afterwards a structured evaluation scores the transcript against the recruiter's own criteria.",
    "Two React apps, ~50 Cloud Functions and Python services on Cloud Run, a multi-tenant Firestore layer with TOTP MFA and role-based access. In pilot with real hiring teams; cut manual screening effort by roughly 90%.",
  ],
  underTheHood: [
    {
      title: "Stopped the speech-to-text model from inventing answers",
      body:
        "Candidates with a muted or dead mic were getting transcript lines they never said — STT models hallucinate on near-silence. Blob size can't detect it. A WebAudio analyser now meters peak loudness during every take and gates silent audio before it ever reaches transcription.",
    },
    {
      title: "Recording pipeline that survives a crash",
      body:
        "WebAudio graph mixing the avatar's voice with the mic into one track, MediaRecorder with a codec-capability cascade (Safari silently recorded nothing on VP8), five-minute chunked uploads with retry, and a Cloud Run FFmpeg merge that re-encodes across sessions — copy-mode left WebM duration metadata broken and players froze at the first boundary.",
    },
    {
      title: "Proctoring in the browser",
      body:
        "MediaPipe face and person detection on an adaptive cycle, iris-based gaze tracking with multi-point calibration and heatmap output, multi-monitor detection via the Screen Enumeration API, and a device fingerprint that catches iPads spoofing desktop mode through touch-point and pointer-media-query contradictions.",
    },
    {
      title: "Keeping a streaming avatar alive past its expiry",
      body:
        "Provider sessions die at ~20 minutes; interviews run to 50. Sessions rotate on a 17-minute schedule and the swap waits for the avatar to finish speaking, with a watchdog on video.currentTime to tell an expiry freeze from a WebRTC drop.",
    },
    {
      title: "Structured evaluation, not prose parsing",
      body:
        "The recruiter's scoring criteria are turned into an OpenAI function-calling schema at submit time — each metric a required numeric field with its criteria as the description — so scores come back typed. A second pass estimates the likelihood that answers were AI-generated.",
    },
  ],
  stack: [
    "React",
    "Next.js",
    "Firebase",
    "Cloud Run",
    "Python",
    "WebRTC",
    "MediaPipe",
    "FFmpeg",
    "OpenAI",
    "Pinecone",
  ],
};

export type Project = {
  title: string;
  blurb: string;
  image: string; // under /public/images
  href: string;
  tags: string[];
  note?: string;
};

export const projects: Project[] = [
  {
    title: "Kochi Metro Rail VR",
    blurb:
      "Station walkthrough simulation for KMRL. Shown to the Governor of Kerala; Best Booth at the 15th Urban Mobility Conference.",
    image: "/images/km.webp",
    href: "https://www.youtube.com/watch?v=e3R1MZmnR-w",
    tags: ["Unity", "OpenXR", "360° video"],
  },
  {
    title: "Kochi Water Metro VR",
    blurb: "Companion simulation of the water-metro terminals for the same KMRL showcase.",
    image: "/images/wm.webp",
    href: "https://www.youtube.com/watch?v=ITmuylA6ypc",
    tags: ["Unity", "OpenXR"],
  },
  {
    title: "Airport Logistics Training",
    blurb:
      "VR onboarding for ground operations. Reported 75% better retention and 4× faster training than the classroom version.",
    image: "/images/atvr.webp",
    href: "https://drive.google.com/file/d/1Hxz0xkzJ5mI2Y1n9TxmHIabys5ufx8QQ/view",
    tags: ["Unity", "Training"],
  },
  {
    title: "Federal Bank — Gold Testing",
    blurb:
      "Procedure training for branch staff: the chemical checks used to verify gold, rebuilt as a hands-on VR module.",
    image: "/images/fb.webp",
    href: "https://drive.google.com/file/d/1SMDjeqQj4UlSI-T0Iged9mvKXSRXUUFg/view",
    tags: ["Unity", "Banking"],
  },
  {
    title: "Faulty Wire Tracing in AR",
    blurb:
      "Digital twin of a vehicle harness. Traces a faulty wire through the real chassis in AR, fed by IoT sensor data.",
    image: "/images/fw.webp",
    href: "https://drive.google.com/file/d/1I_oOc0Wpujjc5qLqiRyOlo3Ph4766b0q/view",
    tags: ["AR", "Digital twin", "IoT"],
  },
  {
    title: "Virtual Tourism",
    blurb: "Photogrammetry-scanned monuments you can walk through in VR.",
    image: "/images/vt.webp",
    href: "https://drive.google.com/file/d/1qcrnDiVZe_6Izs8CDKLxCfD8Tc4YZxFV/view",
    tags: ["Photogrammetry", "VR"],
  },
];

export const alsoBuilt = [
  {
    title: "Britco Mobile Workshop VR",
    blurb: "Multiplayer smartphone-repair classroom (Photon).",
    href: "https://www.youtube.com/watch?v=SR1qXLxUm_w",
  },
  {
    title: "Data Warehouse Safety VR",
    blurb: "Hazard-recognition training for warehouse floors.",
    href: "https://drive.google.com/file/d/1V1y8mkRMl7bD6vvUJWZt67Ts0hpFHQTt/view?usp=sharing",
  },
  {
    title: "Underwater VR",
    blurb: "Marine-ecosystem exploration with custom water shaders.",
    href: null,
  },
  {
    title: "Educational AR apps",
    blurb: "Mobile AR solar system and aquatic-life explorers.",
    href: "https://drive.google.com/drive/folders/1VTybQ_f6It8O1Un0PVseaOn064JDyLv6?usp=sharing",
  },
];

export const roles = [
  {
    when: "Jul 2023 — now",
    title: "Software Developer → Technical Lead",
    org: "NeoRecruit.AI",
    where: "Coimbatore",
    body:
      "Sole engineer on the platform above. Led the move from a Unity WebGL avatar prototype to the React product.",
  },
  {
    when: "Nov 2022 — Jul 2023",
    title: "Unity XR Developer",
    org: "XR Horizon",
    where: "Kochi",
    body:
      "Industrial and transport VR simulations — KMRL, Britco, Federal Bank. Multiplayer environments with Photon; 360° video and OpenXR pipelines.",
  },
  {
    when: "Sep 2021 — Oct 2022",
    title: "Unity Developer, Intern",
    org: "GrahasVR · Nandha Infotech",
    where: "Remote",
    body: "Mobile VR safety training and educational AR for Android.",
  },
];

export const education = {
  when: "2019 — 2023",
  title: "B.Tech, Information Technology",
  org: "Bannari Amman Institute of Technology",
};

export const recognition = [
  {
    title: "Smart India Hackathon 2022",
    body: "National finalist.",
  },
  {
    title: "Best Booth — 15th Urban Mobility Conference",
    body: "For the KMRL VR simulation.",
  },
  {
    title: "WorldSkills 2021",
    body: "Wild-card entrant, 3D Game Art. Later trained students who medalled at BRICS and WorldSkills.",
  },
];
